name: Analysis
on:
  workflow_dispatch:
    inputs:
      total:
        description: The total number of packages to consider
        require: true
        type: number
      page_size:
        description: The page size to fetch from ecosyste.ms (`total` should be `n*page_size`)
        require: true
        type: number

permissions: read-all

jobs:
  npm:
    name: ${{ matrix.target }}, ${{ matrix.metric }}
    runs-on: ubuntu-24.04
    strategy:
      fail-fast: false
      matrix:
        target:
          - go
          - npm
          - rust
        metric:
          - downloads
          - dependent_repos_count
          - docker_dependents_count
          - docker_downloads_count
    env:
      LOG_FILE: ${{ matrix.target }}-${{ matrix.metric }}-${{ inputs.total }}.log
    steps:
      - name: Checkout repository
        uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6.0.1
        with:
          persist-credentials: false
      - name: Go environment
        if: ${{ matrix.target == 'go' }}
        run: |
          echo 'Go'
          go version
      - name: Node.js environment
        if: ${{ matrix.target == 'npm' }}
        run: |
          echo 'Node.js'
          node --version

          echo 'npm'
          npm --version
      - name: Rust environment
        if: ${{ matrix.target == 'rust' }}
        run: |
          echo 'Rust (compiler)'
          rustc --version

          echo 'Cargo'
          cargo --version
      - name: Run analysis
        working-directory: ${{ matrix.target }}
        run: ./pipeline.sh "${TOTAL}" "${PAGE_SIZE}" "${METRIC}" | tee "../${LOG_FILE}"
        env:
          TOTAL: ${{ inputs.total }}
          PAGE_SIZE: ${{ inputs.page_size}}
          METRIC: ${{ matrix.metric }}
      - name: Upload analysis log
        uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # v7.0.1
        with:
          archive: false
          name: ${{ env.LOG_FILE }}
          path: ${{ env.LOG_FILE }}
